plugins {
    id "eclipse"
    id "idea"
    id "war"
    id "io.github.gradle-nexus.publish-plugin"
    id "org.graceframework.grace-web"
    id "org.graceframework.asset-pipeline"
    id "org.graceframework.grace-gsp"
    id "org.graceframework.grace-doc"
}

group "grace.demos"
version projectVersion

repositories {
    mavenCentral()
}

configurations {
    developmentOnly
}

grails {
    plugins {
        implementation project(":plugin")
    }
}

dependencies {
    developmentOnly("org.springframework.boot:spring-boot-devtools")
    console "org.graceframework:grace-console"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.graceframework:grace-boot"
    implementation "org.graceframework:grace-boot-async"
    implementation "org.graceframework:grace-boot-cache"
    implementation "org.graceframework:grace-boot-events"
    implementation "org.graceframework:grace-boot-hibernate"
    implementation "org.graceframework:grace-boot-logging"
    implementation "org.graceframework:grace-boot-persistence"
    implementation "org.graceframework:grace-boot-plugin"
    implementation "org.graceframework:grace-boot-rest"
    implementation "org.graceframework:grace-boot-validation"
    implementation "org.graceframework:grace-boot-web"
    implementation "org.graceframework:grace-plugin-fields"
    implementation "org.graceframework:grace-plugin-gsp"
    implementation "org.graceframework:grace-plugin-scaffolding"
    implementation "org.graceframework:grace-plugin-services"
    implementation "net.datafaker:datafaker:2.7.0"
    profile "org.graceframework.profiles:web"
    runtimeOnly "com.h2database:h2"
    runtimeOnly "org.graceframework.plugins:asset-pipeline-plugin:7.0.0"
    testImplementation "org.graceframework:grace-test-support"
    testImplementation "org.graceframework:grace-plugin-geb"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(Jar) {
    configure {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
}

tasks.withType(GroovyCompile) {
    configure(groovyOptions) {
        forkOptions.jvmArgs = ['-Xmx1024m']
    }
}

tasks.withType(Test) {
    useJUnitPlatform()
    systemProperty "geb.env", System.getProperty('geb.env')
    systemProperty "geb.build.reportsDir", reporting.file("geb/integrationTest")
    systemProperty 'webdriver.chrome.driver', System.getProperty('webdriver.chrome.driver')
    systemProperty 'webdriver.gecko.driver', System.getProperty('webdriver.gecko.driver')
}

assets {
    minifyJs = true
    minifyCss = true
    minifyOptions = [
        languageMode: 'ES6',
        targetLanguage: 'ES6', //Can go from ES6 to ES5 for those bleeding edgers
        optimizationLevel: 'SIMPLE' //Or ADVANCED or WHITESPACE_ONLY
    ]
    skipNonDigests = true
}

publishGuide {
    dependsOn groovydoc
}

tasks.register('docs') { task ->
    task.dependsOn groovydoc, publishGuide
}

nexusPublishing {
    packageGroup = 'org.graceframework.plugins'
    repositories {
        sonatype {
            def mavenUser = System.getenv("MAVEN_CENTRAL_USER") ?: project.hasProperty("mavenCentralUsername") ? project.mavenCentralUsername : ''
            def mavenPass = System.getenv("MAVEN_CENTRAL_PASSWORD") ?: project.hasProperty("mavenCentralPassword") ? project.mavenCentralPassword : ''
            nexusUrl = uri("https://ossrh-staging-api.central.sonatype.com/service/local/")
            snapshotRepositoryUrl = uri("https://central.sonatype.com/repository/maven-snapshots/")
            username = mavenUser
            password = mavenPass
        }
    }
}
